service: aws-connect-apis
# app and org for use with dashboard.serverless.com
app: aws-connect-apis
org: ramshawaseem18

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-2

# you can add statements to the Lambda function's IAM Role here
iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "connect:*"
    Resource: "*"

functions:
  getPhoneNumbersList:
    handler: src/handler.getPhoneNumbersList
    events:
      - http:
          path: getPhoneNumbersList
          method: get
          cors: true
  connectCall:
    handler: src/handler.connectCall
    events:
      - http:
          path: connectCall
          method: post
          cors: true